backend:
  name: git-gateway
  branch: main # Branch que vai mexer no repositório

publish_mode: editorial_workflow # Para fazer um esquema de revisão de novas edições
media_folder: "public/uploads" # Onde os arquivos de mídia serão armazenados
public_folder: "/uploads" # Onde a parte de mídia vai poder ser acessada
#display_url: https://exemplos-da-ide.netlify.app/ # URL que será mostrado no UI do Netlify

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

search: false
locale: 'pt'

collections:
  - name: "membros" # Nome usado da rota
    extension: "json"
    description: "Membros da Relab Jr."
    label: "Membros"
    folder: "content/membros" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    fields: # Campos disponíveis no Netlify
      - {label: "Nome e sobrenome", name: "nome", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Posição", name: "posicao", widget: "select",  options: ["Presidência", "Vice-Presidência", "Projetos", "Administrativo Financeiro", "Comercial", "Gestão de Pessoas", "Marketing", "Trainee"], default: ["Trainee"]}
      - {label: "Linkedin", name: "linkedin", widget: "string", required: false}


  - name: "posts" # Nome usado da rota
    extension: "json"
    description: "Posts da Relab Jr"
    label: "Posts"
    folder: "content/posts" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.titulo}}" # Nome que vai ficar no URL da página
    fields: # Campos disponíveis no Netlify
      - {label: "Visível", name: "bool", widget: "boolean", default: true}
      - {label: "Assunto", name: "assunto", widget: "select", options: ["outros", "economia", "social"], default: ["outros"]}
      - {label: "Autor(a)", name: "autor", widget: "string"}
      - {label: "Data", name: "data", widget: "date", date_format: "DD.MM.YYYY"}
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Conteúdo", name: "conteudo", widget: "markdown"}
      - {label: "Imagem", name: "imagem", widget: "image", required: false}


  - name: "imagensComBotao" # Nome usado da rota
    extension: "json"
    description: "Imagens que vão atrás dos botões de redirecionamento na Home"
    label: "ImagensComBotao"
    folder: "content/imagensComBotao" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    fields: # Campos disponíveis no Netlify
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}


  - name: "imagensInicio" # Nome usado da rota
    extension: "json"
    description: "Imagens no início das páginas"
    label: "ImagensInicio"
    folder: "content/imagensInicio" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    fields: # Campos disponíveis no Netlify
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}


  - name: "paginas"
    label: "Páginas"
    files:
      - label: "Home"
        name: "paginaHome"
        file: "content/paginas/home.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Home"
            name: "inicioHome"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto", name: "texto", widget: "markdown"}


          - label: "Imagem Com Botão Resultados"
            name: "imgbotaoRes"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto", name: "texto", widget: "markdown"}


          - label: "Nossos Serviços"
            name: "servicosHome"
            widget: "object"
            fields:
              - {label: "Serviço 1", name: "servico1", widget: "string"}
              - {label: "Imagem 1", name: "imagem1", widget: "image"}
              - {label: "Serviço 2", name: "servico2", widget: "string"}
              - {label: "Imagem 2", name: "imagem2", widget: "image"}
              - {label: "Serviço 3", name: "servico3", widget: "string"}
              - {label: "Imagem 3", name: "imagem3", widget: "image"}
              - {label: "Serviço 4", name: "servico4", widget: "string"}
              - {label: "Imagem 4", name: "imagem4", widget: "image"}
              - {label: "Serviço 5", name: "servico5", widget: "string"}
              - {label: "Imagem 5", name: "imagem5", widget: "image"}
              - {label: "Serviço 6", name: "servico6", widget: "string"}
              - {label: "Imagem 6", name: "imagem6", widget: "image"}


          - label: "Imagem Com Botão Membros"
            name: "imgbotaoMem"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto", name: "texto", widget: "markdown"}


          - label: "Conteúdo do Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Linkedin", name: "linkedin", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}


      - label: "Página Quem Somos"
        name: "paginaQuemSomos"
        file: "content/paginas/quemSomos.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Quem Somos"
            name: "inicioQuemSomos"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto 1", name: "texto1", widget: "markdown"}
              - {label: "Texto 2", name: "texto2", widget: "markdown"}


          - label: "Carrossel Quem Somos"
            name: "CarrosselQuemSomos"
            widget: "object"
            fields:
              - label: "Imagens Carrossel"
                name: "imagensCarrossel"
                widget: "list"
                min: 3
                max: 10
                field: {label: "Imagem", name: "imagem", widget: "image"}

  # - name: "CarrosselQuemSomos" # Nome usado da rota
  #   extension: "json"
  #   description: "Imagens do carrossel da página Quem Somos"
  #   label: "Carrossel Quem Somos"
  #   folder: "content/carrosselQuemSomos" # Local da pasta onde vão estar os arquivos
  #   fields: # Campos disponíveis no Netlify
  #     - {label: "Ingredients", name: "ingredients", widget: "list", max: 10}
  #     field:
  #     - {label: "Ingredient", name: "ingredient", widget: "string"}

      - label: "Página Serviços"
        name: "paginaServicos"
        file: "content/paginas/servicos.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Serviços"
            name: "inicioServicos"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Texto 1", name: "texto1", widget: "markdown"}
              - {label: "Texto 2", name: "texto2", widget: "markdown"}


      - label: "Página Blog"
        name: "paginaBlog"
        file: "content/paginas/blog.json"
        extension: "json"
        format: "json"
        editor:
        preview: false
        fields:
          - label: "Início Blog"
            name: "inicioBlog"
            widget: "object"
            fields:
              - {label: "Imagem", name: "imagem", widget: "image"}
              - {label: "Título", name: "titulo", widget: "string"}


  - name: "recipe" 
    label: "Recipe" 
    folder: "content/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Photo", name: "photo", widget: "image"}
      - label: "HowToMake"
        name: "howtomake"
        widget: "object"
        fields:
          - label: "Ingredients" 
            name: "ingredients" 
            widget: "list" 
            max: 10
            field: {label: "Ingredient", name: "ingredient", widget: "string"}
          - label: "Instructions"
            name: "instructions"
            widget: "text"