backend:
  name: git-gateway
  branch: main # Branch que vai mexer no repositório

publish_mode: editorial_workflow # Para fazer um esquema de revisão de novas edições
media_folder: "public/uploads" # Onde os arquivos de mídia serão armazenados
public_folder: "/uploads" # Onde a parte de mídia vai poder ser acessada
#display_url: https://exemplos-da-ide.netlify.app/ # URL que será mostrado no UI do Netlify

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

search: false
locale: 'pt'

collections:
  - name: "membros" # Nome usado da rota
    extension: "json"
    description: "Membros da Relab Jr."
    label: "Membros"
    folder: "content/membros" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.nome}}" # Nome que vai ficar no URL da página
    fields: # Campos disponíveis no Netlify
      - {label: "Nome e sobrenome", name: "nome", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Posição", name: "posicao", widget: "select",  options: ["Presidência", "Vice-Presidência", "Projetos", "Administrativo Financeiro", "Comercial", "Gestão de Pessoas", "Marketing", "Trainee"], default: ["Trainee"]}
      - {label: "Linkedin", name: "linkedin", widget: "string", required: false}

  - name: "posts" # Nome usado da rota
    extension: "json"
    description: "Posts da Relab Jr"
    label: "Posts"
    folder: "content/posts" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.titulo}}" # Nome que vai ficar no URL da página
    fields: # Campos disponíveis no Netlify
      - {label: "Visível", name: "bool", widget: "boolean", default: true}
      - {label: "Assunto", name: "assunto", widget: "select", options: ["outros", "economia", "social"], default: ["outros"]}
      - {label: "Autor(a)", name: "autor", widget: "string"}
      - {label: "Data", name: "data", widget: "date", date_format: "DD.MM.YYYY"}
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Conteúdo", name: "conteudo", widget: "markdown"}
      - {label: "Imagem", name: "imagem", widget: "image", required: false}

  - name: "imagensComBotao" # Nome usado da rota
    extension: "json"
    description: "Imagens que vão atrás dos botões de redirecionamento na Home"
    label: "ImagensComBotao"
    folder: "content/imagensComBotao" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.titulo}}" # Nome que vai ficar no URL da página
    fields: # Campos disponíveis no Netlify
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}

  - name: "CarrosselQuemSomos" # Nome usado da rota
    extension: "json"
    description: "Imagens do carrossel da página Quem Somos"
    label: "Carrossel Quem Somos"
    folder: "content/carrosselQuemSomos" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.titulo}}" # Nome que vai ficar no URL da página
    fields: # Campos disponíveis no Netlify
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}


  - name: "imagensInicio" # Nome usado da rota
    extension: "json"
    description: "Imagens no início das páginas"
    label: "ImagensInicio"
    folder: "content/imagensInicio" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    slug: "{{fields.titulo}}" # Nome que vai ficar no URL da página
    fields: # Campos disponíveis no Netlify
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}




  - name: "pages"
    label: "Páginas"
    files:
      - label: "Home"
        name: "paginaHome"
        file: "content/paginas/home.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Conteúdo do Rodapé"
            name: "footer"
            widget: "object"
            fields:
              - {
                  label: "Instagram",
                  name: "instagram",
                  widget: "string",
                  default: "abenrs_",
                }
              - {
                  label: "Email para contato",
                  name: "email",
                  widget: "string",
                  default: "aben-rs@abennacional.org.br",
                }
              - {
                  label: "Telefone para Contato",
                  name: "phone",
                  widget: "string",
                  default: "(51) 3232-3232",
                }
              - {
                  label: "Facebook",
                  name: "facebook",
                  widget: "string",
                  default: "facebook/aben",
                }

      - label: "Página Quem Somos"
        name: "paginaQuemSomos"
        file: "content/paginas/quemSomos.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "Conteúdo da página (HTML)", name: "content", widget: "string" }

      - label: "Página Serviços"
        name: "paginaServicos"
        file: "content/paginas/servicos.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "Conteúdo da página (HTML)", name: "content", widget: "string" }

      - label: "Página Blog"
        name: "paginaBlog"
        file: "content/paginas/blog.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "Conteúdo da página (HTML)", name: "content", widget: "string" }
  
  # - name: "relab-jr" # Nome usado da rota
  #   extension: "json"
  #   description: "Coleção que vai conter todos os campos disponíveis no Netlify CMS."
  #   label: "Todos os modelos" # Nome usado na label do Netlify 
  #   folder: "content/exemplos" # Local da pasta onde vão estar os arquivos
  #   create: true # Permite que usuários criem arquivos nesse local
  #   slug: "{{fields.nome}}" # Nome que vai ficar no URL da página
  #   fields: # Campos disponíveis no Netlify
  #     - {label: "Boolean", name: "bool", widget: "boolean", default: true}
  #     - {label: 'Cor', name: 'cor', widget: 'color', enableAlpha: true, allowInput: true}
  #     - {label: "Título", name: "titulo", widget: "string"}
  #     - {label: "Datas com horário", name: "data", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
  #     - {label: "Arquivos", name: "arquivos", widget: "file", default: "/uploads/neander_VHDL.pdf"}
  #     - {label: "Imagem", name: "imagem", widget: "image"}
  #     - {label: "Localização", name: "localizacao", widget: "map"}
  #     - {label: "Conteúdo", name: "conteudo", widget: "markdown"}
  #     #- {label: "Números", name: "numeros", widget: "number", default: 100, value_type: "float", min: 0, max: 100, step: 0.5}
  #     - {label: "Seleção", name: "selecao", widget: "select", multiple: true, min: 2, max: 3, options: ["um","dois","três"], default: ["dois"]}
  #     - {label: "Texto", name: "texto", widget: "text"}